"""Show the verifier catching a REAL hallucination from RAGTruth.

The live dashboard keeps abstaining because our small generator refuses rather
than fabricates. So this demonstrates the mechanism on REAL labelled data: a
RAGTruth response that ALREADY contains a human-annotated hallucination. For
each sentence we print the verifier's support score and its keep/drop decision
next to the GROUND-TRUTH label, then the corrected (drop) answer.

Run:  python scripts/demo_catch.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from eval.datasets import load_ragtruth
from eval.run_eval import overlaps
from verify.decompose import split_sentences_with_offsets
from verify.nli import get_verifier

THRESHOLD = 0.5  # keep sentence if support >= this


def pick_examples(examples, n=2):
    """QA responses that are hallucinated AND have a green/red mix of sentences."""
    picked = []
    for e in examples:
        if e.task_type != "QA" or not e.hallucinated:
            continue
        sents = split_sentences_with_offsets(e.response)
        if len(sents) < 3:
            continue
        spans = [(s["start"], s["end"]) for s in e.spans]
        bad = [any(overlaps(a, b, sa, sb) for sa, sb in spans) for _, a, b in sents]
        if any(bad) and not all(bad):  # genuine mix
            picked.append((e, sents, bad))
        if len(picked) >= n:
            break
    return picked


def main():
    print("Loading RAGTruth + MiniCheck verifier...\n")
    examples = load_ragtruth(split="test")
    verifier = get_verifier("minicheck")

    for e, sents, bad in pick_examples(examples):
        texts = [s for s, _, _ in sents]
        supports = verifier.support_scores_multi(e.context, texts)

        print("=" * 78)
        print(f"RAGTruth {e.id} (QA) — response generated by {e.meta['model']}")
        print("-" * 78)
        kept = []
        for text, support, gt_bad in zip(texts, supports, bad):
            keep = support >= THRESHOLD
            if keep:
                kept.append(text)
            mark = "DROP (red) " if not keep else "keep (green)"
            truth = "  <-- GROUND-TRUTH HALLUCINATION" if gt_bad else ""
            print(f"  [{mark} {support:4.2f}] {text[:88]}{truth}")
        print("-" * 78)
        print("CORRECTED ANSWER (unsupported sentences removed):")
        print("  " + (" ".join(kept) if kept else "[abstained]"))
        print()


if __name__ == "__main__":
    main()
